/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;
import com.toedter.calendar.JDateChooser;
import javax.swing.JTable;
import controller.barangcontroller;
import controller.datecontroller;
import java.text.ParseException;
import javax.swing.JTextField;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.*;
import java.awt.*;
import koneksi.connector;
import java.sql.Connection;
/**
 *
 * @author Galang
 */
public class BarangView extends javax.swing.JFrame {

    /**
     * Creates new form BarangView
     */
    Connection connection = connector.connection();

    barangcontroller br;
    public BarangView() {
        initComponents();
        br = new barangcontroller(this);
        br.isitabel();
        setTableCellRenderer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTidbarang = new javax.swing.JTextField();
        JTnamabarang = new javax.swing.JTextField();
        JThargabarang = new javax.swing.JTextField();
        JTquantity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnToMain = new javax.swing.JButton();
        JTkadaluarsa = new com.toedter.calendar.JDateChooser();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Barang");
        setPreferredSize(new java.awt.Dimension(920, 450));
        getContentPane().setLayout(null);

        jLabel1.setText("Id Barang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 27, 80, 20);

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(17, 53, 80, 20);

        jLabel4.setText("Harga Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(17, 79, 80, 20);

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(17, 105, 80, 20);

        jLabel6.setText("Kadaluarsa");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(17, 128, 80, 20);

        JTidbarang.setEditable(false);
        JTidbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTidbarangActionPerformed(evt);
            }
        });
        getContentPane().add(JTidbarang);
        JTidbarang.setBounds(131, 24, 180, 20);
        getContentPane().add(JTnamabarang);
        JTnamabarang.setBounds(131, 50, 180, 20);
        getContentPane().add(JThargabarang);
        JThargabarang.setBounds(131, 76, 180, 20);
        getContentPane().add(JTquantity);
        JTquantity.setBounds(131, 102, 180, 20);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        btnToMain.setText("Ke Menu Utama");
        btnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMainActionPerformed(evt);
            }
        });
        jPanel2.add(btnToMain);
        btnToMain.setBounds(10, 340, 130, 23);
        jPanel2.add(JTkadaluarsa);
        JTkadaluarsa.setBounds(120, 120, 180, 20);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus);
        btnHapus.setBounds(211, 190, 90, 23);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah);
        btnUbah.setBounds(110, 190, 90, 23);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(10, 190, 90, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 9, 340, 390);

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 10, 536, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTidbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTidbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTidbarangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        br.insert();
        br.isitabel();
        setTableCellRenderer();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        br.update();
        br.isitabel();
        setTableCellRenderer();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        br.delete();
        br.isitabel();
        hapusField();
        setTableCellRenderer();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int baris = tabelBarang.getSelectedRow();
        JTidbarang.setText(tabelBarang.getValueAt(baris,0).toString());
        JTnamabarang.setText(tabelBarang.getValueAt(baris,1).toString());
        JThargabarang.setText(tabelBarang.getValueAt(baris,2).toString());
        JTquantity.setText(tabelBarang.getValueAt(baris,3).toString());
        Object nilaiTanggal = tabelBarang.getValueAt(baris, 4);
        if (nilaiTanggal != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date tanggal = dateFormat.parse(nilaiTanggal.toString());
                JTkadaluarsa.setDate(tanggal);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMainActionPerformed
        // TODO add your handling code here:
        MainView main = new MainView();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangView().setVisible(true);
            }
        });
    }
    
    private void setTableCellRenderer() { 
        datecontroller dt = new datecontroller();
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column){
                Component component = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row,
                        column);
                
                component.setForeground(Color.BLACK);
                Object nilaiTanggal = tabelBarang.getValueAt(row, 4);
                if (nilaiTanggal != null) {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    try {
                        Date tanggal = dateFormat.parse(nilaiTanggal.toString());
                        if(dt.compareDate(tanggal) == 1){
                            component.setForeground(Color.RED);
                        }
                        else {
                            component.setBackground(table.getBackground());
                        }
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                }
                return component;
            }
        };
        for (int i = 0; i < tabelBarang.getColumnCount(); i++) {
            tabelBarang.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JThargabarang;
    private javax.swing.JTextField JTidbarang;
    private com.toedter.calendar.JDateChooser JTkadaluarsa;
    private javax.swing.JTextField JTnamabarang;
    private javax.swing.JTextField JTquantity;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnToMain;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables

    
    
    public JTable getTabelBarang() {
        return tabelBarang;
    }

    public void setTabelBarang(JTable tabelBarang) {
        this.tabelBarang = tabelBarang;
    }

    public JTextField getJThargabarang() {
        return JThargabarang;
    }

    public void setJThargabarang(JTextField JThargabarang) {
        this.JThargabarang = JThargabarang;
    }

    public JTextField getJTidbarang() {
        return JTidbarang;
    }

    public void setJTidbarang(JTextField JTidbarang) {
        this.JTidbarang = JTidbarang;
    }

    public JDateChooser getJTkadaluarsa() {
        return JTkadaluarsa;
    }

    public void setJTkadaluarsa(JDateChooser JTkadaluarsa) {
        this.JTkadaluarsa = JTkadaluarsa;
    }

    public JTextField getJTnamabarang() {
        return JTnamabarang;
    }

    public void setJTnamabarang(JTextField JTnamabarang) {
        this.JTnamabarang = JTnamabarang;
    }

    public JTextField getJTquantity() {
        return JTquantity;
    }

    public void setJTquantity(JTextField JTquantity) {
        this.JTquantity = JTquantity;
    }
    
    public void hapusField(){
        JTidbarang.setText("");
        JTnamabarang.setText("");
        JThargabarang.setText("");
        JTquantity.setText("");
        JTkadaluarsa.setDate(null);
    }
}
