/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import controller.cartcontroller;
import java.text.NumberFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class NotaView extends javax.swing.JFrame {

    /**
     * Creates new form NotaView
     */
    cartcontroller cr;
    public NotaView() {
        CartView c = new CartView();
        initComponents();
        cr = new cartcontroller(c);
        

    }
    
   
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLkembali = new javax.swing.JLabel();
        JLtotalnota = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JTtunai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnselesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");
        setMinimumSize(new java.awt.Dimension(494, 326));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        JLkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLkembali.setForeground(new java.awt.Color(255, 255, 255));
        JLkembali.setText("-");
        jPanel1.add(JLkembali);
        JLkembali.setBounds(170, 130, 160, 40);

        JLtotalnota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLtotalnota.setForeground(new java.awt.Color(255, 255, 255));
        JLtotalnota.setText("0");
        jPanel1.add(JLtotalnota);
        JLtotalnota.setBounds(170, 50, 170, 40);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayar);
        btnBayar.setBounds(360, 100, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Belanja :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 110, 40);
        jPanel1.add(JTtunai);
        JTtunai.setBounds(170, 100, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tunai              : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembalian     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 110, 40);

        btnselesai.setText("Selesai");
        btnselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselesaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnselesai);
        btnselesai.setBounds(340, 240, 110, 23);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali);
        btnKembali.setBounds(30, 240, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        hitungKembalian();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselesaiActionPerformed
        // TODO add your handling code here:
        if(hitungKembalian() == 1){
            cr.updateHistory();
            cr.hapusCart();
            MainView main = new MainView();
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnselesaiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        CartView cart = new CartView();
        cart.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaView().setVisible(true);
            }
        });
    }
    
    public int hitungKembalian(){
        try{
            NumberFormat ribuan = NumberFormat.getInstance();
            
            int total = Integer.parseInt(getJLtotalnota().getText());
            int tunai = Integer.parseInt(getJTtunai().getText());
            if(tunai < total){
                throw new InterruptedException();
            }
            else{
                int kembali = tunai - total;
                getJLkembali().setText((String.valueOf(ribuan.format(kembali))));
                return 1;
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Input Salah!", "Error", JOptionPane.ERROR_MESSAGE);
            getJTtunai().setText("");
        }catch(InterruptedException er){
            JOptionPane.showMessageDialog(this, "Uang Tunai Kurang!", "Error", JOptionPane.ERROR_MESSAGE);
            getJTtunai().setText("");
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLkembali;
    private javax.swing.JLabel JLtotalnota;
    private javax.swing.JTextField JTtunai;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnselesai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getJLtotalnota() {
        return JLtotalnota;
    }

    public void setJLtotalnota(JLabel JLtotalnota) {
        this.JLtotalnota = JLtotalnota;
    }

    public JButton getBtnSelesai() {
        return btnBayar;
    }

    public void setBtnSelesai(JButton btnSelesai) {
        this.btnBayar = btnSelesai;
    }

    public JLabel getJLkembali() {
        return JLkembali;
    }

    public void setJLkembali(JLabel JLkembali) {
        this.JLkembali = JLkembali;
    }

    public JTextField getJTtunai() {
        return JTtunai;
    }

    public void setJTtunai(JTextField JTtunai) {
        this.JTtunai = JTtunai;
    }
    
    
}
